(require 'url)

(defvar stucchio-dropbox "c:/Users/stucc/Dropbox/")
(defvar stucchio-org-papers-directory "file:papers/")
(defvar stucchio-org-papers-absolute-directory (concat stucchio-dropbox "org/papers/"))
(defvar stucchio-org-papers-default-download-directory "c:/Users/stucc/Downloads/")

(defun stucchio-org-humanize-filename (filename title)
  (let ((title-underscorified (replace-regexp-in-string "\\W+" "_" title))
        (fn (file-name-nondirectory filename))
        )
    (concat title-underscorified "__" fn)
    )
  )

(defun stucchio-org-move-to-papers (title)
  "Moves a file from anywhere into my org-mode papers directory. Specific location is determined by the stucchio-org-papers-directory variable."
  (interactive "sTitle of paper:")
  (let ((source-file (read-file-name "File to import: " stucchio-org-papers-default-download-directory))
        (cleaned-title (replace-regexp-in-string "\\W+" " " title))
        )
    (let ((base-filename (stucchio-org-humanize-filename source-file title)))
      (let ((dest-file-absolute (concat stucchio-org-papers-absolute-directory base-filename))
            (dest-file-org (concat stucchio-org-papers-directory base-filename)))
        (rename-file source-file dest-file-absolute)
        (org-insert-link nil dest-file-org cleaned-title)
        (message (concat "Moved " source-file " to " dest-file-org))
        )
      )
    )
  )

(defun stucchio-org-get-for-papers (title url)
  "Pulls a file from the web  into my org-mode papers directory. Specific location is determined by the stucchio-org-papers-directory variable."
  (interactive "sTitle of paper: \nsURL: ")

  (let ((cleaned-title (replace-regexp-in-string "\n+" " " title))
        (filename (file-name-nondirectory (url-filename (url-generic-parse-url url))))
        )
    (let ((dest-file (stucchio-org-humanize-filename (concat stucchio-org-papers-absolute-directory filename) title)))
      (url-copy-file url (concat stucchio-org-papers-absolute-directory dest-file))
      (org-insert-link nil (concat stucchio-org-papers-directory dest-file) cleaned-title)
      (org-set-property "original-source" url)
      (message (concat "Retrieved document " cleaned-title " from " url ", stored at " dest-file))
      )
    )
  )
